{
 "title": "Apps",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "type", "label": "Type", "query": "PREFIX.*" },
   { "name": "site", "label": "System", "query": "PREFIX.$type.*" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "PREFIX.$type.$site.memory.internal"
    }
   ]
  },
  {
   "title": "Child Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "PREFIX.$type.$site.childprocess.pool.*.busy"
    }
   ]
  },
  {
   "title": "Recoil Pool",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "PREFIX.$type.$site.recoil.pool.busy"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "PREFIX.$type.$site.parallel.pool.*.busy"
    }
   ]
  },
  {
   "title": "Ticks",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.ticks.*.ticks, 6)"
    },
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.streams.read.ticks, 6)"
    },
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.streams.write.ticks, 6)"
    },
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.timers.*.ticks, 6)"
    }
   ]
  },
  {
   "title": "Req/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "target": "PREFIX.$type.$site.http-server.reqs.total"
    }
   ]
  },
  {
   "title": "Avg req time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "PREFIX.$type.$site.http-server.reqs.took.average"
    }
   ]
  },
  {
   "title": "IO In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "target": "PREFIX.$type.$site.eventloop.io.read"
    }
   ]
  },
  {
   "title": "IO Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "target": "PREFIX.$type.$site.eventloop.io.write"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(PREFIX.$type.$site.memory.*, 5)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(PREFIX.$type.$site.cpu.usage, 5)"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.streams.read.current, 6, 7)"
    },
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.streams.write.current, 6, 7)"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.io.*, 6)"
    }
   ]
  },
  {
   "title": "Ticks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.ticks.future.ticks, 6, 7)"
    },
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.*.*.ticks, 5, 6)"
    }
   ]
  },
  {
   "title": "Timers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(PREFIX.$type.$site.eventloop.timers.*.current, 6)"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(PREFIX.$type.$site.parallel.pool.*.*, 6, 7)"
    }
   ]
  }
 ]
}